### ISSUE TITLE
Widgets not loading while switching profiles 

### ISSUE THREAD

**Issue by sahalkabeer** [zobnin/aio#132] opened 2024-10-13 11:32 UTC
**Describe the bug**

I created different profiles with different widgets including android and built-in . After saving the profiles and while switching between them some of the widgets are not loaded and it shows an error saying something went terribly wrong.
Also the my app widget got completely disappeared from the list.

**To Reproduce**

1. Create profiles with some widgets 
2. Add my app widget and add your apps
3. Add android widgets 
4. Save profile 
5. Create 2 or more profiles like this (with different apps in my apps widgets)
6. Try switching the profiles 

**Expected behavior**

Widgets to load properly 

**Screenshots**

Attached 

**Smartphone (please complete the following information):**

 - Device: Google Pixel 7
 - Android version: Android 15 Beta
 - AIO Version: 5.4.2

**Additional context**

A
![Screenshot_20241013-151650](https://github.com/user-attachments/assets/095f90bb-6965-4858-8254-4831d70b2a1c)
![Screenshot_20241013-151623](https://github.com/user-attachments/assets/12c17a06-9c15-423e-9fed-135a8a446c8f)
dd any other context about the problem here.

**Comment by zobnin** [comment] 2024-10-13 11:37
Please fill all fields. Closing.

**Closed as completed by zobnin** 2024-10-13 11:37 UTC

**Comment by sahalkabeer** [comment] 2024-10-14 12:24
All Fields are filled

**Comment by sahalkabeer** [comment] 2024-10-14 12:25
> Please fill all fields. Closing.

I had filled it, forgot to delete these <>

**Comment by zobnin** [comment] 2024-10-14 12:42
"Tap to add widget" means that you have deleted the widget manually from some profiles. If you want widget to be in some profile do not delete it from other profile. It is Android limitation, not AIO.

About my apps widget: can't reproduce.

**Comment by mj-sson** [comment] 2024-11-14 00:29
I think your problem with the 'My apps' widgets was solved in the AIO 5.4.3 Version. It is now also possible to have different 'My apps' widgets with different sets of apps, in different profiles 😀
