### ISSUE TITLE
Conversations widget partially closes before opening

### ISSUE THREAD

**Issue by TheQwervy** [zobnin/aio#140] opened 2024-12-17 05:27 UTC
**Describe the bug**

The first time the conversation widget is triggered by a new conversation it shows in the folded state. Unfolding the widget however minimizes it so it's just the card an additional two presses are required to return to the unfold state and then finally unfold. 

**To Reproduce**

1. Receive a new conversation
2. Unfold the widget (but it glitches and folds even further)
3. Unfold widget back to the folded state
4. Unfold widget fully to the unfolded state

**Expected behavior**

A singular unfold should fully unfold the conversation widget on the first click. Just like the notifications widget

**Screenshots**

**Smartphone (please complete the following information):**

I will send a screenshot if the extra folded conversation card once this occurs again

**Comment by TheQwervy** [comment] 2024-12-17 08:31
![Screenshot_20241217-162947 (1).png](https://github.com/user-attachments/assets/ce94ecd2-990c-4694-af30-2f2e34390c3c)

**Comment by zobnin** [comment] 2024-12-18 01:38
I couldn't reproduce this issue.

If automatic folding is enabled, the widget initially displays the line "Messages: X," where X is the number of messages. After expanding, the widget shows the text of the messages.

If auto folding is disabled and the widget is expanded, it immediately displays the text of the messages.

**Comment by TheQwervy** [comment] 2024-12-18 03:05
Yeah, I'm not sure what's different for me but the behaviour I described is
what I get for some reason

**Comment by zobnin** [comment] 2024-12-18 09:05
I was able to reproduce your issue. It only occurs if the app's activity is killed, for example, when Android does it automatically or if you have enabled option to fix the freezing issue on Android 14/15.

Will be fixed in the next version.

**Closed as completed by zobnin** 2024-12-18 09:05 UTC
Labels: bug

**Comment by TheQwervy** [comment] 2024-12-18 09:09
Wow, thanks for finding the issue so quickly, I'm glad that it will be
fixed in the next version!

**Comment by TheQwervy** [comment] 2024-12-20 16:03
@zobnin I think this new glitch I found is related to the previous glitch potentially so I'll send the video here.

https://github.com/user-attachments/assets/43917eb1-0285-4002-911d-4284ea0d6a06

Conversation not clearing and when clearing tile becomes blank and requires fold-unfold to become "normal". 

Conversation persists for a while even though message has been read and notification has been cleared on the android side.

The video is from after I already read and replied to the message and cleared all notifications related to that message.
